### ISSUE TITLE
Nothing is show out in creative cloud

### ISSUE THREAD

**Issue by Nakxion** [corbindavenport/creative-cloud-linux#75] opened 2019-08-23 19:19 UTC
I installed it with no errors at all but when I open it's shown nothing as you see In screenshot
I have fedora 30 btw
[Error](https://i.ibb.co/TgMz58T/Screenshot-20190823-211002.png)

**Comment by corbindavenport** [comment] 2019-08-23 21:19
Yes, because it can't access the internet. This is a duplicate of #52.

**Closed by corbindavenport** 2019-08-23 21:19 UTC
