### ISSUE TITLE
Adobe-server isn't reachable

### ISSUE THREAD

**Issue by DrumPhil95** [corbindavenport/creative-cloud-linux#53] opened 2018-07-15 10:28 UTC
After entering my dates to the creative cloud login in the last step of the installation an error occurred and mentioned that the adobe server isn't reachable and I've to check my firewall settings. 

Turning off the firewall hasn't brought any benefit. Any suggestions, I'd be grateful.

**Comment by Ytses** [comment] 2018-07-22 21:35
I second this. 
![screenshot from 2018-07-23 01-31-41](https://user-images.githubusercontent.com/35729141/43050376-e7a454fe-8e07-11e8-986b-7fac0ab64ca8.png)

**Comment by JamesFromEdinburgh** [comment] 2018-07-25 12:48
Thirded, I too get this message.

**Comment by corbindavenport** [comment] 2018-07-28 01:51
Duplicate of #49

**Closed by corbindavenport** 2018-07-28 01:51 UTC
