### ISSUE TITLE
Creative Cloud update BUG

### ISSUE THREAD

**Issue by rebeluarte** [corbindavenport/creative-cloud-linux#55] opened 2018-07-26 13:05 UTC
Hi, i'm having problem to install the scritp in my Deepin OS 15.6. Truly, i install, but the problem happens when i try to install any programs from creative cloud, because they don't update, just stay in (0%) I wait during 30 minutes and nothing happens, please, tell me how can i fix
![deepin screenshot_creative cloud exe_20180726100356](https://user-images.githubusercontent.com/41743365/43264039-5e3b2ec0-90bb-11e8-8ede-13a19b33af2c.png)

**Comment by rrfaria** [comment] 2018-07-27 20:07
I have same problem.
I've tried change the url to download zip from adobe but I also had the same issue, now I can't login. I've used this one:
https://helpx.adobe.com/download-install/kb/creative-cloud-apps-download.html
and get app link there.

I tried update wine and OS but same issue . I can't login: 

See my changes:
```shell
#!/usr/bin/env bash
# Date : (02-15-2018)
# Distribution used to test : Ubuntu 17.10 x64
# Author : Corbin Davenport
# Licence : GPLv3
# PlayOnLinux: 4.2.12

# Based on RoninDusette's script
# from https://www.playonlinux.com/en/app-2316-Adobe_Photoshop_CS6.html

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

PREFIX="CreativeCloud2018"
WINEVERSION="3.13"
TITLE="Adobe Creative Cloud"
EDITOR="Adobe Systems Inc."
GAME_URL="http://www.adobe.com"
AUTHOR="Corbin Davenport"


#Initialization
POL_SetupWindow_Init
POL_SetupWindow_SetID 3251

POL_Debug_Init

# Presentation
POL_SetupWindow_presentation "$TITLE" "$EDITOR" "$GAME_URL" "$AUTHOR" "$PREFIX"

# Create prefix and temporary download folder
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WINEVERSION"
POL_System_TmpCreate "CreativeCloud"
Set_OS "win8"

# Install dependencies
POL_SetupWindow_wait "Please wait while dependences are installed..." "$TITLE"
POL_Call POL_Install_msxml3
# adicionado a mais
#Dependencies
POL_Call POL_Install_AdobeAir
POL_Call POL_Install_atmlib
POL_Call POL_Install_gdiplus
POL_Call POL_Install_msxml6
POL_Call POL_Install_vcrun2005
POL_Call POL_Install_vcrun2008
POL_Call POL_Install_vcrun2010
POL_Call POL_Install_vcrun2012
POL_Call POL_Install_vcrun2013
POL_Call POL_Install_vcrun2015
POL_Call POL_Install_corefonts
POL_Call POL_Install_tahoma2
POL_Call POL_Install_FontsSmoothRGB

cd "$POL_System_TmpDir"
# Use winetricks, since the POL_corefonts version does not work with the installer
POL_Download_Resource  "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
POL_SetupWindow_wait "Please wait while winetricks is installed... (this might take a few minutes)" "$TITLE"
chmod +x winetricks
./winetricks atmlib corefonts fontsmooth=rgb

# Get the installer
cd "$POL_System_TmpDir"
#POL_Download "http://ccmdl.adobe.com/AdobeProducts/KCCC/1/win32/ACCCx4_5_0_331.zip"
POL_Download "http://prdl-download.adobe.com/Photoshop/66A1D1E00DE44601B041A631261EC584/1507845150875/AdobePhotoshop19-mul.zip"
POL_SetupWindow_wait "Please wait while the installer is extracted..." "$TITLE"
unzip *.zip
INSTALLER="$POL_System_TmpDir/Set-up.exe"

# Run the installer
POL_Wine_WaitBefore "$TITLE"
POL_Wine "$INSTALLER"
POL_Shortcut "Creative Cloud.exe" "Adobe Creative Cloud"
POL_System_TmpDelete

# All done
POL_SetupWindow_message "$(eval_gettext 'The installation is now complete, you can now use the Adobe Creative Cloud manager to download the applications you need.\n\nNOTE: The Creative Cloud manager takes a while to log in, and you may see an error meessage. That is completely normal - don't close the login window!\n\nAfter you download an app, you can add a PlayOnLinux shortcut for it by clicking ADOBE CREATIVE CLOUD in the app list, clicking CONFIGURE, and clicking MAKE A NEW SHORTCUT FROM THIS VIRTUAL DRIVE. Then look for the app, like Photoshop.exe, and add it.')" "$TITLE"

POL_SetupWindow_Close
exit 0

```

**Comment by rebeluarte** [comment] 2018-07-27 22:56
u can install IE7 after the installation, in the playonlinux, i'm going to try and i send you an answer

**Comment by corbindavenport** [comment] 2018-07-28 01:53
Duplicate of #52

**Closed by corbindavenport** 2018-07-28 01:53 UTC
