### ISSUE TITLE
Apps tab not loading

### ISSUE THREAD

**Issue by android4682** [corbindavenport/creative-cloud-linux#62] opened 2018-09-15 08:54 UTC
I've installed creative cloud successfully with the installation script provided on this repo.
However when I press the Apps tab to start installing some apps, it loads for awhile and then jumps back to the Stock tab.

This is the error it gave: https://pastebin.com/tZq3v5aQ

I'm running Ubuntu 18.04.1 and I'm using the recommended wine version and packages (since it's all installed by the script)

**Comment by corbindavenport** [comment] 2018-09-15 20:01
Duplicate of #59, I'll move your changelog over there.

**Closed by corbindavenport** 2018-09-15 20:01 UTC
