### ISSUE TITLE
No OpenGL Support

### ISSUE THREAD

**Issue by chrisribal** [corbindavenport/creative-cloud-linux#1] opened 2017-10-09 15:44 UTC
Finally! Finnaly i can design with a working version of Photoshop using linux! Thank you so much!

In my installation (Ubuntu 16.04) Photoshop claims that OpenGL is inactive and Photoshop has not enough VRAM to use some features. I have an NVidia GTX 950 with 4 GB VRAM, but Wine seems not to be recognizing the drivers. Do you know how i can make it using them? And maybe you can improve your script to cover that point?

**Comment by corbindavenport** [comment] 2017-10-10 23:17
I'll look into this, but it may be a Wine-related bug and not something I can fix.

**Comment by MrKoookaburra** [comment] 2017-10-12 04:19
It's not a bug at all. In playonlinux, goto configure > display > video memory size.

**Comment by corbindavenport** [comment] 2017-10-12 19:27
Ah sweet. I'll close this and add a note to the readme about it.

**Closed by corbindavenport** 2017-10-12 19:27 UTC

**Comment by cowai** [comment] 2017-10-15 12:05
@corbindavenport @MrKoookaburra setting the video memory size does not help with my Nvidia 770.

**Comment by parrotgeek1** [comment] 2017-10-18 03:41
sudo apt-get install libgl1-nvidia-glx:i386

**Comment by cowai** [comment] 2017-10-18 18:01
@parrotgeek1 That package is not available in Ubuntu 17.04 at least.

**Comment by parrotgeek1** [comment] 2017-10-18 18:32
I apologise, I copied and pasted that from a forum without testing it
