### ISSUE TITLE
Cant Start adobe creative cloud 

### ISSUE THREAD

**Issue by monty88** [corbindavenport/creative-cloud-linux#70] opened 2019-04-08 08:24 UTC
![Screenshot from 2019-04-08 11-23-41](https://user-images.githubusercontent.com/18521185/55709404-e590b580-59f0-11e9-844c-e6369d7cd7ca.png)
Please help to fix that

**Comment by monty88** [comment] 2019-04-08 08:26
I am using ubuntu 18.04

**Comment by Colangjas** [comment] 2019-04-18 14:50
I'm getting this same error. Here's the error details:

Unhandled exception: unimplemented function KERNEL32.dll.GetQueuedCompletionStatusEx called in 32-bit code (0x7bc7aee0).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7bc7aee0 ESP:00c4e5f0 EBP:00c4e654 EFLAGS:00000202(   - --  I   - - - )
 EAX:00600722 EBX:7bd0c5c4 ECX:00c4e6a4 EDX:00110060
 ESI:00c4e5fc EDI:7b47e2b0
Stack dump:
0x00c4e5f0:  0014d5f8 00000000 00c4e620 80000100
0x00c4e600:  00000001 00000000 7bc7aee0 00000002
0x00c4e610:  00600f8e 00600722 00000034 00110014
0x00c4e620:  0014d5f8 00000000 00c4e64c 7bd0c5c4
0x00c4e630:  00000000 0014d5f8 00c4e658 005681b2
0x00c4e640:  8d7ee3d9 01d4f5f5 005681b2 7bd0c5c4
Backtrace:
=>0 0x7bc7aee0 call_dll_entry_point+0x580() in ntdll (0x00c4e654)
  1 0x0034000f (0x00c4e9d4)
  2 0x0044f108 in agmservice (+0x4f107) (0x00c4e9e8)
  3 0x7bcad864 call_thread_func_wrapper+0xb() in ntdll (0x00c4ea08)
  4 0x7bcb10ad in ntdll (+0x710ac) (0x00c4eae8)
  5 0x7bcad842 RtlRaiseException+0x49() in ntdll (0x00c4eb08)
  6 0x7bcb8f8c in ntdll (+0x78f8b) (0x00c4f358)
  7 0xf7cc63a6 start_thread+0xf5() in libpthread.so.0 (0x00c4f428)
  8 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  9 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  10 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  11 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  12 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  13 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  14 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  15 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  16 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  17 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  18 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  19 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  20 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  21 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  22 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  23 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  24 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  25 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  26 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  27 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  28 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  29 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  30 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  31 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  32 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  33 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  34 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  35 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  36 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  37 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  38 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  39 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  40 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  41 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  42 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  43 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  44 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  45 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  46 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  47 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  48 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  49 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  50 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  51 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  52 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  53 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  54 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  55 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  56 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  57 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  58 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  59 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  60 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  61 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  62 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  63 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  64 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  65 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  66 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  67 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  68 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  69 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  70 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  71 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  72 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  73 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  74 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  75 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  76 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  77 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  78 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  79 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  80 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  81 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  82 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  83 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  84 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  85 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  86 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  87 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  88 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  89 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  90 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  91 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  92 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  93 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  94 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  95 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  96 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  97 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  98 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  99 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  100 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  101 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  102 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  103 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  104 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  105 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  106 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  107 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  108 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  109 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  110 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  111 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  112 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  113 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  114 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  115 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  116 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  117 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  118 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  119 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  120 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  121 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  122 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  123 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  124 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  125 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  126 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  127 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  128 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  129 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  130 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  131 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  132 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  133 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  134 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  135 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  136 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  137 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  138 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  139 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  140 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  141 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  142 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  143 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  144 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  145 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  146 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  147 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  148 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  149 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  150 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  151 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  152 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  153 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  154 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  155 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  156 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  157 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  158 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  159 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  160 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  161 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  162 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  163 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  164 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  165 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  166 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  167 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  168 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  169 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  170 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  171 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  172 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  173 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  174 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  175 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  176 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  177 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  178 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  179 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  180 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  181 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  182 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  183 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  184 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  185 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  186 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  187 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  188 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  189 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  190 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  191 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  192 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  193 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  194 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  195 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  196 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  197 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  198 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  199 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
  200 0xf7bde4d6 __clone+0x65() in libc.so.6 (0x00000000)
0x7bc7aee0 call_dll_entry_point+0x580 in ntdll: subl	$4,%esp
Modules:
Module	Address			Debug info	Name (97 modules)
PE	  400000-  64b000	Export          agmservice
ELF	7b400000-7b7f6000	Deferred        kernel32<elf>
  \-PE	7b420000-7b7f6000	\               kernel32
ELF	7bc00000-7bd2b000	Dwarf           ntdll<elf>
  \-PE	7bc40000-7bd2b000	\               ntdll
ELF	7c000000-7c003000	Deferred        <wine-loader>
ELF	7d579000-7d597000	Deferred        libgcc_s.so.1
ELF	7d5c7000-7d5da000	Deferred        api-ms-win-core-sysinfo-l1-2-1<e
PE	7d5d0000-7d5da000	Deferred        api-ms-win-core-sysinfo-l1-2-1
PE	7d5da000-7d5ed000	Deferred        api-ms-win-core-localization-l1-
PE	7d5e0000-7d5ed000	Deferred        api-ms-win-core-localization-l1-C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
ELF	7d5ed000-7d610000	Deferred        libgpg-error.so.0
ELF	7d610000-7d75d000	Deferred        libp11-kit.so.0
ELF	7d767000-7d77a000	Deferred        api-ms-win-core-fibers-l1-1-1<el
PE	7d770000-7d77a000	Deferred        api-ms-win-core-fibers-l1-1-1
ELF	7d77a000-7d78d000	Deferred        api-ms-win-core-synch-l1-2-0<elf
PE	7d780000-7d78d000	Deferred        api-ms-win-core-synch-l1-2-0
ELF	7d78d000-7d812000	Deferred        libgcrypt.so.11
ELF	7d812000-7d8db000	Deferred        libgnutls.so.26
ELF	7d8db000-7d915000	Deferred        uxtheme<elf>
  \-PE	7d8e0000-7d915000	\               uxtheme
ELF	7da4e000-7da80000	Deferred        libexpat.so.1
ELF	7da80000-7daca000	Deferred        libfontconfig.so.1
ELF	7dad6000-7dadf000	Deferred        libffi.so.6
ELF	7dadf000-7daf1000	Deferred        libtasn1.so.3
ELF	7dafa000-7db96000	Deferred        libfreetype.so.6
ELF	7db96000-7dbbb000	Deferred        imm32<elf>
  \-PE	7dba0000-7dbbb000	\               imm32
ELF	7dbbb000-7dbf1000	Deferred        wintrust<elf>
  \-PE	7dbc0000-7dbf1000	\               wintrust
ELF	7dbf1000-7dc11000	Deferred        bcrypt<elf>
  \-PE	7dc00000-7dc11000	\               bcrypt
ELF	7dc11000-7dce5000	Deferred        crypt32<elf>
  \-PE	7dc20000-7dce5000	\               crypt32
ELF	7dce5000-7dd15000	Deferred        netapi32<elf>
  \-PE	7dcf0000-7dd15000	\               netapi32
ELF	7dd15000-7dd2d000	Deferred        userenv<elf>
  \-PE	7dd20000-7dd2d000	\               userenv
ELF	7dd2d000-7dd6d000	Deferred        winhttp<elf>
  \-PE	7dd30000-7dd6d000	\               winhttp
ELF	7dd6d000-7dde1000	Deferred        setupapi<elf>
  \-PE	7dd80000-7dde1000	\               setupapi
ELF	7dde1000-7ddf9000	Deferred        libresolv.so.2
ELF	7de0c000-7de29000	Deferred        jsproxy<elf>
  \-PE	7de10000-7de29000	\               jsproxy
ELF	7de29000-7de53000	Deferred        iphlpapi<elf>
  \-PE	7de30000-7de53000	\               iphlpapi
ELF	7de53000-7de92000	Deferred        ws2_32<elf>
  \-PE	7de60000-7de92000	\               ws2_32
ELF	7de92000-7df0f000	Deferred        wininet<elf>
  \-PE	7dea0000-7df0f000	\               wininet
ELF	7df0f000-7e1f2000	Deferred        shell32<elf>
  \-PE	7df20000-7e1f2000	\               shell32
ELF	7e21d000-7e226000	Deferred        libuuid.so.1
ELF	7e226000-7e246000	Deferred        cabinet<elf>
  \-PE	7e230000-7e246000	\               cabinet
ELF	7e246000-7e26e000	Deferred        mpr<elf>
  \-PE	7e250000-7e26e000	\               mpr
ELF	7e26e000-7e287000	Deferred        libz.so.1
ELF	7e287000-7e3b6000	Deferred        comctl32<elf>
  \-PE	7e290000-7e3b6000	\               comctl32
ELF	7e3b6000-7e3d0000	Deferred        aclui<elf>
  \-PE	7e3c0000-7e3d0000	\               aclui
ELF	7e3d0000-7e44c000	Deferred        shlwapi<elf>
  \-PE	7e3e0000-7e44c000	\               shlwapi
ELF	7e44c000-7e595000	Deferred        oleaut32<elf>
  \-PE	7e460000-7e595000	\               oleaut32
ELF	7e595000-7e61d000	Deferred        rpcrt4<elf>
  \-PE	7e5a0000-7e61d000	\               rpcrt4
ELF	7e61d000-7e753000	Deferred        gdi32<elf>
  \-PE	7e630000-7e753000	\               gdi32
ELF	7e753000-7e944000	Deferred        user32<elf>
  \-PE	7e770000-7e944000	\               user32
ELF	7e944000-7e9c3000	Deferred        advapi32<elf>
  \-PE	7e950000-7e9c3000	\               advapi32
ELF	7e9c3000-7eb2d000	Deferred        ole32<elf>
  \-PE	7e9e0000-7eb2d000	\               ole32
ELF	7eb2d000-7ebd2000	Deferred        urlmon<elf>
  \-PE	7eb40000-7ebd2000	\               urlmon
ELF	7ebd2000-7ecec000	Deferred        msi<elf>
  \-PE	7ebe0000-7ecec000	\               msi
ELF	7ecec000-7ed00000	Deferred        libnss_files.so.2
ELF	7ed00000-7ed1b000	Deferred        libnsl.so.1
ELF	7ed1b000-7ed29000	Deferred        libnss_nis.so.2
ELF	7ed29000-7ed33000	Deferred        libnss_compat.so.2
ELF	7eece000-7efd0000	Deferred        libm.so.6
ELF	7efd3000-7efe6000	Deferred        psapi<elf>
  \-PE	7efe0000-7efe6000	\               psapi
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7ae2000-f7ae7000	Deferred        libdl.so.2
ELF	f7ae7000-f7cc0000	Dwarf           libc.so.6
ELF	f7cc0000-f7cdf000	Dwarf           libpthread.so.0
ELF	f7d05000-f7d0f000	Deferred        librt.so.1
ELF	f7d0f000-f7edf000	Dwarf           libwine.so.1
ELF	f7ee1000-f7f09000	Deferred        ld-linux.so.2
ELF	f7f0c000-f7f0e000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	[C:\windows\system32\services.exe]
	0000005b    0
	00000057    0
	00000133    0
	00000119    0
	00000114    0
	0000001d    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	0000001c    0
	00000017    0
	00000016    0
	00000012    0
0000001a plugplay.exe
	[C:\windows\system32\plugplay.exe]
	0000001f    0
	0000001e    0
	0000001b    0
00000029 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	0000002d    0
	0000002c    0
	0000002b    0
	0000002a    0
00000112 svchost.exe
	[C:\windows\system32\svchost.exe -k netsvcs]
	00000121    0
	00000116    0
	00000115    0
	00000113    0
00000117 rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000001a7    0
	0000011d    0
	0000011c    0
	0000011b    0
	0000011a    0
	00000118    0
00000128 Adobe Installer.exe
	["C:\Program Files\Common Files\Adobe\Adobe Desktop Common\ElevationManager\Adobe Installer.exe" --pipename={C782D1EA-A4FB-482C-94FD-538CAF1E0157} ]
	000001ce    0
	00000129    0
0000012f AdobeUpdateService.exe
	["C:\Program Files\Common Files\Adobe\Adobe Desktop Common\ElevationManager\AdobeUpdateService.exe"]
	000001aa    0
	000001a9    0
	00000136    0
	00000135    0
	00000134    0
	00000130    0
00000131 Creative Cloud.exe
	["C:\Program Files\Adobe\Adobe Creative Cloud\ACC\Creative Cloud.exe" --appletID=CCM_UI --workflow=CCM_workflow_launch --appletVersion=1.0 --mode=LBS --helperBridgeName={2947B6B9-E32F-41F8-8AB0-04DA43ED64E2} --lbsWorkflowID={D8A71E31-3311-49C6-833A-56E54AAA7508} --lbsInstallerWorkflowID={D21801A8-8518-4BCE-BF9C-6966E99A2B1D} --userGuid=]
	00000206    0
	000001db    0
	000001a6    0
	00000185    0
	00000166    0
	00000161    0
	00000160    0
	0000015e    0
	0000015d    0
	0000015c    0
	0000015b    0
	0000015a    0
	00000159    0
	00000158    0
	00000157    0
	00000156    0
	00000155    0
	00000154    0
	00000153    0
	00000152    0
	00000151   -2
	00000150   -2
	0000014f    0
	0000014e    0
	0000014d    0
	0000014c    0
	0000014b    0
	0000014a    0
	00000149    0
	00000148    0
	00000147    0
	00000146    0
	00000141    0
	00000140    0
	0000013a    0
	00000139    0
	00000138    0
	00000137    0
	00000132    0
0000013b AdobeIPCBroker.exe
	["C:\Program Files\Common Files\Adobe\OOBE\PDApp\IPC\AdobeIPCBroker.exe" "-launchedbyvulcan-305 C:\Program Files\Adobe\Adobe Creative Cloud\ACC\Creative Cloud.exe"]
	00000198    0
	00000176    0
	0000016d    0
	00000165    0
	0000013f    0
	0000013e    0
	0000013d    0
	0000013c    0
00000167 Adobe CEF Helper.exe
	["C:\Program Files\Common Files\Adobe\Adobe Desktop Common\HEX\Adobe CEF Helper.exe" --type=renderer --disable-3d-apis --disable-pinch --no-sandbox --disable-databases --primordial-pipe-token=8A3B4DE5CC21F861B822A62F425ACB51 --lang=en-US --lang=en-US --locales-dir-path="C:\Program Files\Common Files\Adobe\Adobe Desktop Common\CEF\locales" --log-file="C:\users\colin\Temp\CreativeCloud\ACC\CEF.log" --log-severity=warning --user-agent="Mozilla/5.0 (Windows NT 6.1.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36 CreativeCloud/4.5.0.331" --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --disable-webrtc-hw-vp8-encoding --disable-gpu-compositing --service-request-channel-token=8A3B4DE5CC21F861B822A62F425ACB51 --renderer-client-id=2 --mojo-platform-channel-handle=916 /prefetch:1]
	00000183    0
	00000182   -2
	00000181    0
	00000180    0
	0000017f    0
	0000017e    0
	0000017d    0
	0000017c    0
	0000017b    0
	0000017a    0
	00000179    0
	00000178    0
	0000016c    0
	0000016b    0
	00000168    0
0000016e Adobe Desktop Service.exe
	["C:\Program Files\Common Files\Adobe\Adobe Desktop Common\ADS\Adobe Desktop Service.exe" --appletID=CCM_UI --appletVersion=1.0 --helperBridgeName={2947B6B9-E32F-41F8-8AB0-04DA43ED64E2} --lbsInstallerWorkflowID={D21801A8-8518-4BCE-BF9C-6966E99A2B1D} --lbsWorkflowID={D8A71E31-3311-49C6-833A-56E54AAA7508} --mode=LBS --workflow=CCM_workflow_launch --waitForRegistration=true]
	00000077    0
	00000031    0
	00000032    0
	0000000a    0
	0000000b    0
	00000207    0
	000001dd    0
	000001d8    0
	000001d5    0
	000001cf    0
	000001cc    0
	000001ca    0
	000001c9    0
	000001c8    0
	000001c7    0
	000001c6    0
	000001c5    0
	000001c4    0
	000001c3   -1
	000001c2    0
	000001c1    0
	000001c0    0
	000001bf    0
	000001bd   -1
	000001bc   -1
	000001b9    0
	000001b8    0
	000001b7    0
	000001b6    0
	000001b5    0
	000001b4    0
	000001b3    0
	000001b2    0
	000001b1    0
	000001b0    0
	000001af    0
	000001ae    0
	000001ad    0
	000001ab    0
	000001a8    0
	00000196    0
	00000195    0
	00000193    0
	00000192    0
	00000191    0
	0000018c    0
	00000187    0
	00000186    0
	00000175    0
	00000174    0
	00000173    0
	00000172    0
	0000016f    0
00000058 AGSService.exe
	["C:\Program Files\Common Files\Adobe\AdobeGCClient\AGSService.exe"]
	00000076    0
	00000054    0
	00000056    0
	0000005a    0
0000005e (D) C:\Program Files\Common Files\Adobe\AdobeGCClient\AGMService.exe
	["C:\Program Files\Common Files\Adobe\AdobeGCClient\AGMService.exe"]
	00000067    0 <==
	00000039    0
	0000003a    0
	00000043    0
	0000005c    0
	0000005d    0
00000063 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	0000006a    0
	00000062    0
	00000061    0
	00000064    0
System information:
    Wine build: wine-2.20 (Staging)
    Platform: i386
    Version: Windows Server 2008 R2
    Host system: Linux
    Host version: 4.15.0-29deepin-generic

**Comment by jabrams2** [comment] 2019-05-13 21:01
I'm getting the same issue. Is this still maintained?

**Comment by corbindavenport** [comment] 2019-05-13 22:33
No one has found a fix yet.

**Comment by dsintrao** [comment] 2019-07-08 20:35
Having the same issue. Any update on this?

**Comment by GuilhermeTokitaka** [comment] 2019-07-18 22:16
Thats my issue too!

**Comment by corbindavenport** [comment] 2019-07-18 23:45
This is a duplicate of #52

**Closed by corbindavenport** 2019-07-18 23:45 UTC
