### ISSUE TITLE
Installer stuck at 2%

### ISSUE THREAD

**Issue by BeeCodingOfc** [corbindavenport/creative-cloud-linux#22] opened 2017-12-31 05:23 UTC
I'm running ubuntu 17.10

I've already tried:
- These commands:
```
sudo apt-get install libcap2-bin
sudo setcap cap_sys_ptrace=eip ~/.PlayOnLinux/wine/linux-x86/2.17-staging/bin/wineserver
sudo setcap cap_sys_ptrace=eip ~/.PlayOnLinux/wine/linux-x86/2.17-staging/bin/wine-preloader
```
They just give a POL_Wine error...
- This command:
`echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`
Wich doesn't change anything (still stuck at 2%)
- When rerunning the script, clicking erase on both solutions

**Comment by BeeCodingOfc** [comment] 2017-12-31 07:19
Update: apparently it has something to do with libgnutls, any thoughts about how to install it?

**Comment by unfulvio** [comment] 2018-01-01 05:29
looks like related to https://github.com/corbindavenport/creative-cloud-linux/issues/17

I'm also looking for a solution to this...

**Comment by corbindavenport** [comment] 2018-01-02 05:22
I think this is a duplicate of #17, so I'll close this one. @BeeCodingOfc, be sure to subscribe to #17 so you still get notifications about the problem.

**Comment by BeeCodingOfc** [comment] 2018-01-02 17:45
sorry @corbindavenport , but I don't think it's the same error. Their logs do not contain libgnutls, which apparently is my problem. (libgnutls makes SSL connections possible). For now, I have installed PS using your script with an Offline installer

**Comment by BeeCodingOfc** [comment] 2018-01-02 17:46
My problem is clearly in the connection between the app and the adobe servers

**Comment by corbindavenport** [comment] 2018-01-05 05:05
Yeah, you might be right. I'll see if I can do something about this, but it may be a Wine bug that I can't fix.

**Comment by corbindavenport** [comment] 2018-02-16 05:57
A brand new version of the install script has been published, can you check if the new update fixes your problem? https://github.com/corbindavenport/creative-cloud-linux/blob/master/README.md

**Comment by Gramps** [comment] 2018-02-17 17:26
New version of the install script does not seem to work for me still.  On Ubuntu 17.10.

**Comment by corbindavenport** [comment] 2018-02-18 02:32
That's good news! I'll close this issue, someone can re-open it if they're still having problems.

**Closed by corbindavenport** 2018-02-18 02:32 UTC
