### ISSUE TITLE
AGMService.exe problem

### ISSUE THREAD

**Issue by joojisan** [corbindavenport/creative-cloud-linux#72] opened 2019-06-18 19:32 UTC
Hello!
I have an issue at the end of the installation, after longing in CC account.
I receive AGMService.exe problem. The progress finished with the update of CC application and then it says a problem with CreativeCloud.exe.
So the installation loading and loading and can not finish...
Sorry if this is known issue, I could not find it.

**Comment by BakaSai** [comment] 2019-07-11 00:37
Yep, same issue here.

**Comment by GuilhermeTokitaka** [comment] 2019-07-18 22:12
Same issue too!

**Comment by corbindavenport** [comment] 2019-07-18 23:44
Duplicate of #52

**Closed by corbindavenport** 2019-07-18 23:44 UTC
